package com.fury.domain;

import java.io.Serializable;
import java.util.Date;

public class user implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.teamer_id
     *
     * @mbg.generated
     */
    private String teamerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.team_id
     *
     * @mbg.generated
     */
    private String teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.ext_info
     *
     * @mbg.generated
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.identity
     *
     * @mbg.generated
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.register_time
     *
     * @mbg.generated
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_t_teamer.is_aval
     *
     * @mbg.generated
     */
    private String isAval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.id
     *
     * @return the value of t_t_teamer.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.id
     *
     * @param id the value for t_t_teamer.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.teamer_id
     *
     * @return the value of t_t_teamer.teamer_id
     *
     * @mbg.generated
     */
    public String getTeamerId() {
        return teamerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.teamer_id
     *
     * @param teamerId the value for t_t_teamer.teamer_id
     *
     * @mbg.generated
     */
    public void setTeamerId(String teamerId) {
        this.teamerId = teamerId == null ? null : teamerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.team_id
     *
     * @return the value of t_t_teamer.team_id
     *
     * @mbg.generated
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.team_id
     *
     * @param teamId the value for t_t_teamer.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.ext_info
     *
     * @return the value of t_t_teamer.ext_info
     *
     * @mbg.generated
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.ext_info
     *
     * @param extInfo the value for t_t_teamer.ext_info
     *
     * @mbg.generated
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.identity
     *
     * @return the value of t_t_teamer.identity
     *
     * @mbg.generated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.identity
     *
     * @param identity the value for t_t_teamer.identity
     *
     * @mbg.generated
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.level
     *
     * @return the value of t_t_teamer.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.level
     *
     * @param level the value for t_t_teamer.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.register_time
     *
     * @return the value of t_t_teamer.register_time
     *
     * @mbg.generated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.register_time
     *
     * @param registerTime the value for t_t_teamer.register_time
     *
     * @mbg.generated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.modify_time
     *
     * @return the value of t_t_teamer.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.modify_time
     *
     * @param modifyTime the value for t_t_teamer.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_t_teamer.is_aval
     *
     * @return the value of t_t_teamer.is_aval
     *
     * @mbg.generated
     */
    public String getIsAval() {
        return isAval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_t_teamer.is_aval
     *
     * @param isAval the value for t_t_teamer.is_aval
     *
     * @mbg.generated
     */
    public void setIsAval(String isAval) {
        this.isAval = isAval == null ? null : isAval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        user other = (user) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTeamerId() == null ? other.getTeamerId() == null : this.getTeamerId().equals(other.getTeamerId()))
            && (this.getTeamId() == null ? other.getTeamId() == null : this.getTeamId().equals(other.getTeamId()))
            && (this.getExtInfo() == null ? other.getExtInfo() == null : this.getExtInfo().equals(other.getExtInfo()))
            && (this.getIdentity() == null ? other.getIdentity() == null : this.getIdentity().equals(other.getIdentity()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getRegisterTime() == null ? other.getRegisterTime() == null : this.getRegisterTime().equals(other.getRegisterTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getIsAval() == null ? other.getIsAval() == null : this.getIsAval().equals(other.getIsAval()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTeamerId() == null) ? 0 : getTeamerId().hashCode());
        result = prime * result + ((getTeamId() == null) ? 0 : getTeamId().hashCode());
        result = prime * result + ((getExtInfo() == null) ? 0 : getExtInfo().hashCode());
        result = prime * result + ((getIdentity() == null) ? 0 : getIdentity().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getRegisterTime() == null) ? 0 : getRegisterTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getIsAval() == null) ? 0 : getIsAval().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", teamerId=").append(teamerId);
        sb.append(", teamId=").append(teamId);
        sb.append(", extInfo=").append(extInfo);
        sb.append(", identity=").append(identity);
        sb.append(", level=").append(level);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isAval=").append(isAval);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}