package com.fury.dao.master;

import com.fury.domain.user;

public interface IUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    int insertSelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    user selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_t_teamer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(user record);
}